MEDICAL COST PREDICTION:
The dataset contains medical information and costs billed by health insurance companies. It contains 1338 rows of data and the following columns: age, gender, BMI, children, smoker, region and insurance charges.
THe model predicts insurance costs according to factors like age, BMI, etc.

IMPORTING LIBRARIES

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

IMPORTING DATASET

In [2]:
dataset = pd.read_csv("/home/kashish/Downloads/insurance.csv")
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,-1].values
Y = Y.reshape(len(Y),1)

In [3]:
dataset.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [33]:
dataset.corr()

age       bmi  children   charges
age       1.000000  0.109272  0.042469  0.299008
bmi       0.109272  1.000000  0.012759  0.198341
children  0.042469  0.012759  1.000000  0.067998
charges   0.299008  0.198341  0.067998  1.000000

In [5]:
dataset['children'].unique()

array([0, 1, 3, 2, 5, 4])

In [6]:
dataset['smoker'].unique()

array(['yes', 'no'], dtype=object)

In [7]:
dataset['sex'].unique()

array(['female', 'male'], dtype=object)

In [8]:
dataset['region'].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

ENCODING CATEGORICAL DATA

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
ct = ColumnTransformer(transformers = [('encoder',ohe,[1,-2,-1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
X[0]

array([1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 19, 27.9, 0], dtype=object)

SPLITTING INTO TRAIN AND TEST SET

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state=1)

In [12]:
X_train

array([[1.0, 0.0, 1.0, ..., 53, 26.6, 0],
       [0.0, 1.0, 1.0, ..., 53, 21.4, 1],
       [0.0, 1.0, 1.0, ..., 18, 37.29, 0],
       ...,
       [1.0, 0.0, 0.0, ..., 51, 34.96, 2],
       [1.0, 0.0, 0.0, ..., 40, 22.22, 2],
       [0.0, 1.0, 1.0, ..., 57, 27.94, 1]], dtype=object)

# Multiple Regression

In [13]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression()

In [14]:
Y_pred = regressor.predict(X_test)

In [15]:
np.set_printoptions(precision=5)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[ 4383.6809   1646.4297 ]
 [12885.03892 11353.2276 ]
 [12589.21653  8798.593  ]
 [13286.22919 10381.4787 ]
 [  544.72833  2103.08   ]
 [32117.58401 38746.3551 ]
 [12919.04237  9304.7019 ]
 [12318.62183 11658.11505]
 [ 3784.29146  3070.8087 ]
 [29468.45725 19539.243  ]
 [11002.81394 12629.8967 ]
 [17539.69474 11538.421  ]
 [ 8681.35472  6338.0756 ]
 [ 8349.04326  7050.642  ]
 [ 3130.12726  1137.4697 ]
 [10445.83896  8968.33   ]
 [ 3863.74358 21984.47061]
 [ 6944.62511  6414.178  ]
 [15009.63121 28287.89766]
 [14441.59912 13462.52   ]
 [12543.65769  9722.7695 ]
 [32958.72553 40932.4295 ]
 [ 9072.63608  8026.6666 ]
 [ 8986.8586   8444.474  ]
 [ 3022.85773  2203.47185]
 [ 8164.97136  6664.68595]
 [ 9556.07558  8606.2174 ]
 [10743.20364  8283.6807 ]
 [ 7694.01744  5375.038  ]
 [ 4373.43772  3645.0894 ]
 [14140.93558 11674.13   ]
 [ 5811.78545 11737.84884]
 [34631.91317 24873.3849 ]
 [27009.11191 33750.2918 ]
 [33348.14099 24180.9335 ]
 [ 9532.96787  9863.4718 ]
 [30421.65018 36837.467  ]
 

In [16]:
from sklearn.metrics import r2_score
print("Accuracy = ",r2_score(Y_test,Y_pred)*100,"%")

Accuracy =  76.23311844057112 %


# Polynomial Regression

In [19]:
from sklearn.preprocessing import PolynomialFeatures
for i in range(2,5):
    poly_reg = PolynomialFeatures(degree=i)
    X_poly = poly_reg.fit_transform(X)
    X_polytrain, X_polytest, Y_polytrain, Y_polytest = train_test_split(X_poly, Y, test_size = 0.2, random_state=1)
    polynom = LinearRegression()
    polynom.fit(X_polytrain, Y_polytrain)
    Y_polypred = polynom.predict(X_polytest)
    print("Accuracy = ",r2_score(Y_polytest,Y_polypred)*100,"%")

Accuracy =  86.21935299452076 %
Accuracy =  84.30427588082942 %
Accuracy =  78.01754510097439 %


The best accuracy is given by polynomial regression with degree=2.

STANDARDIZATION

In [20]:
from sklearn.preprocessing import StandardScaler
sc1 = StandardScaler()
X_train[:,8:] = sc1.fit_transform(X_train[:,8:])
X_test[:,8:] = sc1.transform(X_test[:,8:])
sc2 = StandardScaler()
Y_train = sc2.fit_transform(Y_train)

# Support Vector Regression

In [21]:
from sklearn.svm import SVR
svr_regressor = SVR(kernel = 'rbf')
svr_regressor.fit(X_train, Y_train)
Y_svrpred = sc2.inverse_transform(svr_regressor.predict(X_test))

/home/kashish/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [22]:
np.set_printoptions(precision=5)
print(np.concatenate((Y_svrpred.reshape(len(Y_svrpred),1),sc2.inverse_transform(Y_test).reshape(len(Y_test),1)),1))

[[2.83469e+03 1.98968e+07]
 [1.24909e+04 1.37124e+08]
 [9.95406e+03 1.06272e+08]
 [1.20722e+04 1.25388e+08]
 [1.87893e+03 2.54117e+07]
 [3.62156e+04 4.67945e+08]
 [9.97554e+03 1.12384e+08]
 [1.28025e+04 1.40806e+08]
 [3.52559e+03 3.70988e+07]
 [2.00529e+04 2.35985e+08]
 [1.37488e+04 1.52542e+08]
 [1.27968e+04 1.39360e+08]
 [7.05029e+03 7.65569e+07]
 [8.05519e+03 8.51624e+07]
 [2.36095e+03 1.37502e+07]
 [9.62294e+03 1.08322e+08]
 [3.93502e+03 2.65515e+08]
 [7.54277e+03 7.74759e+07]
 [1.38474e+04 3.41640e+08]
 [1.47037e+04 1.62597e+08]
 [1.09470e+04 1.17433e+08]
 [3.78273e+04 4.94346e+08]
 [9.07164e+03 9.69496e+07]
 [9.62640e+03 1.01995e+08]
 [3.44546e+03 2.66241e+07]
 [7.26307e+03 8.05013e+07]
 [9.29460e+03 1.03949e+08]
 [9.27776e+03 1.00054e+08]
 [6.66860e+03 6.49265e+07]
 [4.09470e+03 4.40342e+07]
 [1.28456e+04 1.40999e+08]
 [5.52162e+03 1.41769e+08]
 [2.17895e+04 3.00404e+08]
 [2.63778e+04 4.07609e+08]
 [2.38430e+04 2.92041e+08]
 [1.06984e+04 1.19132e+08]
 [3.86852e+04 4.44892e+08]
 

In [23]:
print("Accuracy = ",r2_score(Y_test,Y_svrpred)*100,"%")

Accuracy =  86.28653783011315 %


In [24]:
from sklearn.model_selection import train_test_split
X_train1, X_test1, Y_train1, Y_test1 = train_test_split(X, Y, test_size = 0.2, random_state=1)

# Decision Tree Regression

In [25]:
from sklearn.tree import DecisionTreeRegressor
dec_regressor = DecisionTreeRegressor(random_state=0)
dec_regressor.fit(X_train1, Y_train1)

DecisionTreeRegressor(random_state=0)

In [26]:
Y_decpred = dec_regressor.predict(X_test1)

In [27]:
np.set_printoptions(precision=5)
print(np.concatenate((Y_decpred.reshape(len(Y_test1),1),Y_test1.reshape(len(Y_test1),1)),1))

[[ 1263.249    1646.4297 ]
 [11842.62375 11353.2276 ]
 [10848.1343   8798.593  ]
 [10702.6424  10381.4787 ]
 [ 1964.78     2103.08   ]
 [39983.42595 38746.3551 ]
 [ 9048.0273   9304.7019 ]
 [11658.37915 11658.11505]
 [ 3558.62025  3070.8087 ]
 [20296.86345 19539.243  ]
 [24513.09126 12629.8967 ]
 [12105.32    11538.421  ]
 [ 6082.405    6338.0756 ]
 [ 6770.1925   7050.642  ]
 [ 1137.011    1137.4697 ]
 [ 9620.3307   8968.33   ]
 [ 4185.0979  21984.47061]
 [ 5926.846    6414.178  ]
 [14474.675   28287.89766]
 [13844.7972  13462.52   ]
 [ 9140.951    9722.7695 ]
 [39241.442   40932.4295 ]
 [28340.18885  8026.6666 ]
 [ 8782.469    8444.474  ]
 [21344.8467   2203.47185]
 [ 6393.60345  6664.68595]
 [ 6406.4107   8606.2174 ]
 [ 8280.6227   8283.6807 ]
 [ 5836.5204   5375.038  ]
 [ 3558.62025  3645.0894 ]
 [10601.412   11674.13   ]
 [ 5124.1887  11737.84884]
 [35069.37452 24873.3849 ]
 [36898.73308 33750.2918 ]
 [21978.6769  24180.9335 ]
 [10197.7722   9863.4718 ]
 [44585.45587 36837.467  ]
 

In [28]:
print("Accuracy = ",r2_score(Y_test1, Y_decpred)*100,"%")

Accuracy =  74.2980817190692 %


# Random Forest Regression

In [29]:
from sklearn.ensemble import RandomForestRegressor
rand_regressor = RandomForestRegressor(n_estimators=300, random_state=0)
rand_regressor.fit(X_train1, Y_train1)
y_randpred = rand_regressor.predict(X_test1)

<ipython-input-29-5e6ecbffd0b8>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rand_regressor.fit(X_train1, Y_train1)


In [30]:
np.set_printoptions(precision=5)
print(np.concatenate((y_randpred.reshape(len(Y_test1),1),Y_test1.reshape(len(Y_test1),1)),1))

[[ 1590.12705  1646.4297 ]
 [12018.04489 11353.2276 ]
 [ 9246.24458  8798.593  ]
 [11294.21544 10381.4787 ]
 [ 2212.78628  2103.08   ]
 [40122.04141 38746.3551 ]
 [10002.95323  9304.7019 ]
 [11665.03385 11658.11505]
 [ 4336.52955  3070.8087 ]
 [19869.1717  19539.243  ]
 [16798.38818 12629.8967 ]
 [12264.00443 11538.421  ]
 [ 6851.04514  6338.0756 ]
 [ 7059.17967  7050.642  ]
 [ 1608.10128  1137.4697 ]
 [11032.91297  8968.33   ]
 [ 5554.688   21984.47061]
 [ 6888.62584  6414.178  ]
 [17201.21671 28287.89766]
 [13525.09841 13462.52   ]
 [11940.2712   9722.7695 ]
 [41527.54539 40932.4295 ]
 [12320.81984  8026.6666 ]
 [11284.87843  8444.474  ]
 [14522.05572  2203.47185]
 [ 6574.3651   6664.68595]
 [12583.83867  8606.2174 ]
 [10115.31494  8283.6807 ]
 [ 7596.25838  5375.038  ]
 [ 3970.50174  3645.0894 ]
 [12523.93518 11674.13   ]
 [ 6663.26755 11737.84884]
 [26429.91779 24873.3849 ]
 [34886.53198 33750.2918 ]
 [25583.56617 24180.9335 ]
 [12833.32547  9863.4718 ]
 [39833.36035 36837.467  ]
 

In [31]:
print("Accuracy = ",r2_score(Y_test1, y_randpred)*100,"%")

Accuracy =  85.52443578267392 %


The best accuracy is given by the SVR model.